# Auto-generated PyDI integration script
# Generated by Groq LLaMA - IntegrationAgent

from PyDI.io import load_parquet, load_csv, load_xml
from PyDI.entitymatching import StandardBlocker, TokenBlocker
from PyDI.entitymatching import StringComparator, NumericComparator
from PyDI.entitymatching import RuleBasedMatcher
from PyDI.fusion import (
    DataFusionStrategy,
    DataFusionEngine,
    longest_string,
    union,
    prefer_higher_trust,
)
from PyDI.schemamatching import LLMBasedSchemaMatcher
from PyDI.llm import ChatLLM
import pandas as pd
import numpy as np
import os

# Define dataset paths
DATA_DIR = "datasets/"

# Define API Key
os.environ["GOOGLE_API_KEY"] = "<API-KEY>"

# Load the first dataset
amazon = load_parquet(
    DATA_DIR + "amazon.parquet",
    name="amazon",
)

# Load goodreads dataset
goodreads = load_parquet(
    DATA_DIR + "goodreads.parquet",
    name="goodreads",
)

# Load metabooks dataset
metabooks = load_parquet(
    DATA_DIR + "metabooks.parquet",
    name="metabooks",
)

datasets = [amazon, goodreads, metabooks]

# Perform Schema Matching (LLM-based matching)
print("Matching Schema")

llm = ChatLLM(
    model="gemini-2.0-flash",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=2,
)

matcher = LLMBasedSchemaMatcher(chat_model=llm, num_rows=10, debug=True)

# Match schema of amazon with goodreads and rename schema of goodreads
schema_correspondences = matcher.match(amazon, goodreads)
rename_map = schema_correspondences.set_index("target_column")[
    "source_column"
].to_dict()
goodreads = goodreads.rename(columns=rename_map)

# Match schema of amazon with metabooks and rename schema of metabooks
schema_correspondences = matcher.match(amazon, metabooks)
rename_map = schema_correspondences.set_index("target_column")[
    "source_column"
].to_dict()
metabooks = metabooks.rename(columns=rename_map)

# Perform Entity Matching
print("Performing Blocking")

# Define blocking in this example using the TokenBlocker
blocker_amazon_goodreads = TokenBlocker(
    amazon,
    goodreads,
    on=["title", "author"],
    batch_size=1000,
    output_dir="output/blocking-evaluation",
    id_column="id",
)

blocker_amazon_metabooks = TokenBlocker(
    amazon,
    metabooks,
    on=["title", "author"],
    batch_size=1000,
    output_dir="output/blocking-evaluation",
    id_column="id",
)

# Define comparators
comparators = [
    # Title similarity
    StringComparator(
        column="title",
        similarity_function="jaccard",
    ),
    # Author similarity
    StringComparator(
        column="author",
        similarity_function="jaccard",
    ),
    # Rating similarity
    NumericComparator(
        column="rating",
        max_difference=1,
    ),
]

print("Matching Entities")

# Initialize Rule-Based Matcher
matcher = RuleBasedMatcher()

rb_correspondences_amazon_goodreads = matcher.match(
    df_left=amazon,
    df_right=goodreads,
    candidates=blocker_amazon_goodreads,
    comparators=comparators,
    weights=[
        0.4,
        0.3,
        0.3,
    ],
    threshold=0.7,
    id_column="id",
)

rb_correspondences_amazon_metabooks = matcher.match(
    df_left=amazon,
    df_right=metabooks,
    candidates=blocker_amazon_metabooks,
    comparators=comparators,
    weights=[0.4, 0.3, 0.3],
    threshold=0.7,
    id_column="id",
)

print("Fusing Data")

# Data Fusion
# Set trust scores. You may draw your own assumptions about which dataset should be trusted most
amazon.attrs["trust_score"] = 3
goodreads.attrs["trust_score"] = 2
metabooks.attrs["trust_score"] = 1

# Merge rule-based correspondences
all_rb_correspondences = pd.concat(
    [rb_correspondences_amazon_goodreads, rb_correspondences_amazon_metabooks],
    ignore_index=True,
)

# Define data fusion strategy
strategy = DataFusionStrategy("book_fusion_strategy")

strategy.add_attribute_fuser("title", longest_string)
strategy.add_attribute_fuser("author", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("rating", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("language", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("genres", union)

# Run fusion
engine = DataFusionEngine(
    strategy,
    debug=True,
    debug_format="json",
    debug_file="output/data_fusion/debug_fusion_rb_token_blocker.jsonl",
)

# Fuse rule-based matches
rb_fused_token_blocker = engine.run(
    datasets=[amazon, goodreads, metabooks],
    correspondences=all_rb_correspondences,
    id_column="id",
    include_singletons=False,
)

# Write output
rb_fused_token_blocker.to_csv(
    "output/data_fusion/fusion_rb_token_blocker.csv", index=False
)
