# Auto-generated PyDI integration script
# Generated by Groq LLaMA - IntegrationAgent

from PyDI.io import load_parquet
from PyDI.entitymatching import StandardBlocker, TokenBlocker
from PyDI.entitymatching import StringComparator, NumericComparator, DateComparator
from PyDI.entitymatching import RuleBasedMatcher
from PyDI.fusion import (
    DataFusionStrategy,
    DataFusionEngine,
    longest_string,
    union,
    prefer_higher_trust,
)
from PyDI.schemamatching import LLMBasedSchemaMatcher
from langchain_google_genai import ChatGoogleGenerativeAI

import pandas as pd
import numpy as np
import os
import logging

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)-5s] %(name)s - %(message)s",
    handlers=[logging.FileHandler("output/logs/pydi.log"), logging.StreamHandler()],
    force=True,
)

# Define dataset paths
DATA_DIR = "datasets/"

# Define API Key
os.environ["GOOGLE_API_KEY"] = "<API-KEY>"

# Load the datasets
amazon_dataset = load_parquet(
    DATA_DIR + "amazon.parquet",
    name="amazon",
)

goodreads_dataset = load_parquet(
    DATA_DIR + "goodreads.parquet",
    name="goodreads",
)

metabooks_dataset = load_parquet(
    DATA_DIR + "metabooks.parquet",
    name="metabooks",
)

datasets = [amazon_dataset, goodreads_dataset, metabooks_dataset]

# Perform Schema Matching (LLM-based matching)
llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=2,
)

matcher = LLMBasedSchemaMatcher(chat_model=llm, num_rows=10, debug=True)

# match schema of amazon with goodreads and rename schema of goodreads
schema_correspondences = matcher.match(amazon_dataset, goodreads_dataset)
rename_map = schema_correspondences.set_index("target_column")[
    "source_column"
].to_dict()
goodreads_dataset = goodreads_dataset.rename(columns=rename_map)

# match schema of amazon with metabooks and rename schema of metabooks
schema_correspondences = matcher.match(amazon_dataset, metabooks_dataset)
rename_map = schema_correspondences.set_index("target_column")[
    "source_column"
].to_dict()
metabooks_dataset = metabooks_dataset.rename(columns=rename_map)

# Perform Entity Matching
blocker_amazon_goodreads = StandardBlocker(
    amazon_dataset,
    goodreads_dataset,
    on=["title", "author"],
    batch_size=1000,
    output_dir="output/blocking-evaluation",
    id_column="id",
)

blocker_amazon_metabooks = StandardBlocker(
    amazon_dataset,
    metabooks_dataset,
    on=["title", "author"],
    batch_size=1000,
    output_dir="output/blocking-evaluation",
    id_column="id",
)

comparators = [
    StringComparator(
        column="title",
        similarity_function="jaccard",
    ),
    StringComparator(
        column="author",
        similarity_function="jaccard",
    ),
    StringComparator(
        column="isbn_clean",
        similarity_function="jaccard",
    ),
]

matcher = RuleBasedMatcher()

rb_correspondences_amazon_goodreads = matcher.match(
    df_left=amazon_dataset,
    df_right=goodreads_dataset,
    candidates=blocker_amazon_goodreads,
    comparators=comparators,
    weights=[0.4, 0.3, 0.3],
    threshold=0.7,
    id_column="id",
)

rb_correspondences_amazon_metabooks = matcher.match(
    df_left=amazon_dataset,
    df_right=metabooks_dataset,
    candidates=blocker_amazon_metabooks,
    comparators=comparators,
    weights=[0.4, 0.3, 0.3],
    threshold=0.7,
    id_column="id",
)

# Data Fusion
amazon_dataset.attrs["trust_score"] = 3
goodreads_dataset.attrs["trust_score"] = 2
metabooks_dataset.attrs["trust_score"] = 1

all_rb_correspondences = pd.concat(
    [rb_correspondences_amazon_goodreads, rb_correspondences_amazon_metabooks],
    ignore_index=True,
)

strategy = DataFusionStrategy("book_fusion_strategy")

strategy.add_attribute_fuser("title", longest_string)
strategy.add_attribute_fuser("author", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("isbn_clean", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("rating", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("numratings", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("language", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("genres", union)
strategy.add_attribute_fuser("bookformat", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("edition", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("page_count", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("publisher", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser(
    "publish_year", prefer_higher_trust, trust_key="trust_score"
)
strategy.add_attribute_fuser("price", prefer_higher_trust, trust_key="trust_score")

engine = DataFusionEngine(
    strategy,
    debug=True,
    debug_format="json",
    debug_file="output/data_fusion/debug_fusion_rb_standard_blocker.jsonl",
)

rb_fused_standard_blocker = engine.run(
    datasets=[amazon_dataset, goodreads_dataset, metabooks_dataset],
    correspondences=all_rb_correspondences,
    id_column="id",
    include_singletons=False,
)

rb_fused_standard_blocker.to_csv(
    "output/data_fusion/fusion_rb_standard_blocker.csv", index=False
)


def main(file_paths):
    # Load datasets
    datasets = [load_parquet(file_path) for file_path in file_paths]

    # Perform schema matching, entity matching, and data fusion
    # ... (same code as above)


if __name__ == "__main__":
    file_paths = ["amazon.parquet", "goodreads.parquet", "metabooks.parquet"]
    main(file_paths)
