# Auto-generated PyDI integration script
# Generated by Groq LLaMA - IntegrationAgent

from PyDI.io import load_parquet
from PyDI.entitymatching import StandardBlocker, TokenBlocker
from PyDI.entitymatching import StringComparator, NumericComparator
from PyDI.entitymatching import RuleBasedMatcher
from PyDI.fusion import (
    DataFusionStrategy,
    DataFusionEngine,
    longest_string,
    union,
    prefer_higher_trust,
)
from PyDI.schemamatching import LLMBasedSchemaMatcher
from langchain_groq import ChatGroq

import pandas as pd
import numpy as np
import os
import logging

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)-5s] %(name)s - %(message)s",
    handlers=[logging.FileHandler("output/logs/pydi.log"), logging.StreamHandler()],
    force=True,
)

# Define dataset paths
DATA_DIR = "datasets/"

# Load the datasets
amazon = load_parquet(
    DATA_DIR + "amazon.parquet",
    name="amazon",
)

goodreads = load_parquet(
    DATA_DIR + "goodreads.parquet",
    name="goodreads",
)

metabooks = load_parquet(
    DATA_DIR + "metabooks.parquet",
    name="metabooks",
)

datasets = [amazon, goodreads, metabooks]

# Define a unified schema
unified_schema = {
    "id": "object",
    "title": "object",
    "author": "object",
    "rating": "float64",
    "numratings": "Int64",
    "language": "string",
    "genres": "string",
    "bookformat": "string",
    "edition": "string",
    "page_count": "Int32",
    "publisher": "string",
    "publish_year": "Int16",
    "price": "float64",
    "isbn_clean": "string",
}

# Normalize each dataset to the unified schema
for dataset in datasets:
    dataset = dataset.astype(unified_schema)

# Perform schema matching
llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.2)


matcher = LLMBasedSchemaMatcher(chat_model=llm, num_rows=10, debug=True)


schema_correspondences = matcher.match(amazon, goodreads)
rename_map = schema_correspondences.set_index("target_column")[
    "source_column"
].to_dict()
goodreads = goodreads.rename(columns=rename_map)

schema_correspondences = matcher.match(amazon, metabooks)
rename_map = schema_correspondences.set_index("target_column")[
    "source_column"
].to_dict()
metabooks = metabooks.rename(columns=rename_map)

# Perform blocking
blocker_amazon_goodreads = StandardBlocker(
    amazon,
    goodreads,
    on=["title"],
    batch_size=1000,
    output_dir="output/blocking-evaluation",
    id_column="id",
)

blocker_amazon_metabooks = StandardBlocker(
    amazon,
    metabooks,
    on=["title"],
    batch_size=1000,
    output_dir="output/blocking-evaluation",
    id_column="id",
)

# Define comparators
comparators = [
    StringComparator(
        column="title",
        similarity_function="jaccard",
    ),
    StringComparator(
        column="author",
        similarity_function="jaccard",
        preprocess=str.lower,
    ),
    NumericComparator(
        column="rating",
        max_difference=1,
    ),
]

# Perform entity matching
matcher = RuleBasedMatcher()

correspondences_amazon_goodreads = matcher.match(
    df_left=amazon,
    df_right=goodreads,
    candidates=blocker_amazon_goodreads,
    comparators=comparators,
    weights=[0.5, 0.3, 0.2],
    threshold=0.7,
    id_column="id",
)

correspondences_amazon_metabooks = matcher.match(
    df_left=amazon,
    df_right=metabooks,
    candidates=blocker_amazon_metabooks,
    comparators=comparators,
    weights=[0.5, 0.3, 0.2],
    threshold=0.7,
    id_column="id",
)

# Perform data fusion
strategy = DataFusionStrategy("book_fusion_strategy")

strategy.add_attribute_fuser("title", longest_string)
strategy.add_attribute_fuser("author", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("rating", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("numratings", union)
strategy.add_attribute_fuser("language", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("genres", union)
strategy.add_attribute_fuser("bookformat", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("edition", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("page_count", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("publisher", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser(
    "publish_year", prefer_higher_trust, trust_key="trust_score"
)
strategy.add_attribute_fuser("price", prefer_higher_trust, trust_key="trust_score")
strategy.add_attribute_fuser("isbn_clean", longest_string)

engine = DataFusionEngine(
    strategy,
    debug=True,
    debug_format="json",
    debug_file="output/data_fusion/debug_fusion.jsonl",
)

# Set trust scores
amazon.attrs["trust_score"] = 3
goodreads.attrs["trust_score"] = 2
metabooks.attrs["trust_score"] = 1

# Merge rule based correspondences
all_correspondences = pd.concat(
    [correspondences_amazon_goodreads, correspondences_amazon_metabooks],
    ignore_index=True,
)

# Run fusion
fused_data = engine.run(
    datasets=[amazon, goodreads, metabooks],
    correspondences=all_correspondences,
    id_column="id",
    include_singletons=False,
)

# Write output
fused_data.to_csv("output/data_fusion/fusion_output.csv", index=False)


def main(file_paths):
    # Load datasets
    datasets = [load_parquet(file_path) for file_path in file_paths]

    # Perform schema matching, blocking, entity matching, and data fusion
    # ... (same code as above)

    # Write output
    fused_data.to_csv("output/data_fusion/fusion_output.csv", index=False)


if __name__ == "__main__":
    file_paths = [
        "datasets/amazon.parquet",
        "datasets/goodreads.parquet",
        "datasets/metabooks.parquet",
    ]
    main(file_paths)
