# Auto-generated PyDI integration script
# Generated by Groq LLaMA - IntegrationAgent

from PyDI.io import load_parquet
from PyDI.entitymatching import TokenBlocker, StringComparator, RuleBasedMatcher
from PyDI.fusion import (
    DataFusionStrategy,
    DataFusionEngine,
    longest_string,
    union,
    prefer_higher_trust,
)
import pandas as pd
import numpy as np
import os

def main(file_paths):
    # Load datasets
    datasets = []
    for file_path in file_paths:
        dataset = load_parquet(file_path)
        dataset.columns = [col.lower().replace("_", "") for col in dataset.columns]
        datasets.append(dataset)

    # Define unified schema
    unified_schema = {
        "title": "object",
        "author": "object",
        "rating": "float64",
        "numratings": "Int64",
        "publisher": "string",
        "publishyear": "Int16",
        "isbnclean": "string",
    }

    # Normalize datasets to unified schema
    normalized_datasets = []
    for dataset in datasets:
        normalized_dataset = dataset.copy()
        for col, dtype in unified_schema.items():
            if col not in normalized_dataset.columns:
                normalized_dataset[col] = None
            normalized_dataset[col] = normalized_dataset[col].astype(dtype)
        normalized_datasets.append(normalized_dataset)

    # Concatenate normalized datasets
    concatenated_dataset = pd.concat(normalized_datasets, ignore_index=True)

    # Perform blocking
    blocker = TokenBlocker(
        concatenated_dataset,
        on="title",
        batch_size=1000,
        output_dir="output/blocking-evaluation",
        id_column="id",
    )

    # Perform matching
    comparators = [
        StringComparator(
            column="title",
            similarity_function="jaccard",
            preprocess=str.lower,
        ),
        StringComparator(
            column="author",
            similarity_function="jaccard",
            preprocess=str.lower,
        ),
        StringComparator(
            column="isbnclean",
            similarity_function="jaccard",
            preprocess=str.lower,
        ),
    ]
    matcher = RuleBasedMatcher()
    correspondences = matcher.match(
        df_left=concatenated_dataset,
        df_right=concatenated_dataset,
        candidates=blocker,
        comparators=comparators,
        weights=[0.5, 0.3, 0.2],
        threshold=0.7,
        id_column="id",
    )

    # Perform data fusion
    strategy = DataFusionStrategy("book_fusion_strategy")
    strategy.add_attribute_fuser("title", longest_string)
    strategy.add_attribute_fuser("author", prefer_higher_trust, trust_key="trust_score")
    strategy.add_attribute_fuser("rating", prefer_higher_trust, trust_key="trust_score")
    strategy.add_attribute_fuser("numratings", prefer_higher_trust, trust_key="trust_score")
    strategy.add_attribute_fuser("publisher", prefer_higher_trust, trust_key="trust_score")
    strategy.add_attribute_fuser("publishyear", prefer_higher_trust, trust_key="trust_score")
    strategy.add_attribute_fuser("isbnclean", union)
    engine = DataFusionEngine(
        strategy,
        debug=True,
        debug_format="json",
        debug_file="output/data_fusion/debug_fusion.jsonl",
    )
    fused_dataset = engine.run(
        datasets=normalized_datasets,
        correspondences=correspondences,
        id_column="id",
        include_singletons=False,
    )

    # Write output
    fused_dataset.to_csv("output/data_fusion/fusion.csv", index=False)

if __name__ == "__main__":
    file_paths = [
        "datasets/amazon.parquet",
        "datasets/goodreads.parquet",
        "datasets/metabooks.parquet",
    ]
    main(file_paths)
