# Auto-generated PyDI integration script
# Generated by Groq LLaMA - IntegrationAgent

from PyDI.io import load_parquet
from PyDI.entitymatching import (
    TokenBlocker,
    RuleBasedMatcher,
    StringComparator,
)
from PyDI.fusion import (
    DataFusionStrategy,
    DataFusionEngine,
    longest_string,
    union,
    prefer_higher_trust,
)
from PyDI.schemamatching import LLMBasedSchemaMatcher
import pandas as pd
import numpy as np
import os


def normalize_dataset(df, unified_schema):
    # Normalize column names to lowercase and remove underscores
    df.columns = [col.lower().replace("_", "") for col in df.columns]

    # Add missing columns and cast types
    for col in unified_schema:
        if col not in df.columns:
            df[col] = None
        if unified_schema[col] == "string":
            df[col] = df[col].astype(str)
        elif unified_schema[col] == "int":
            df[col] = pd.to_numeric(df[col], errors="coerce")
        elif unified_schema[col] == "float":
            df[col] = pd.to_numeric(df[col], errors="coerce")

    return df


def main(file_paths):
    # Load datasets
    datasets = []
    for file_path in file_paths:
        df = load_parquet(file_path)
        datasets.append(df)

    # Define unified schema
    unified_schema = {
        "title": "string",
        "author": "string",
        "rating": "float",
        "numratings": "int",
        "publisher": "string",
        "publishyear": "int",
        "isbn_clean": "string",
    }

    # Normalize datasets to unified schema
    normalized_datasets = []
    for df in datasets:
        normalized_df = normalize_dataset(df, unified_schema)
        normalized_datasets.append(normalized_df)

    # Concatenate normalized datasets
    concatenated_df = pd.concat(normalized_datasets, ignore_index=True)

    # Perform blocking
    blocker = TokenBlocker(
        concatenated_df,
        concatenated_df,
        column="title",
        ngram_size=3,
        batch_size=1000,
    )
    candidates = blocker.materialize()

    # Perform matching
    comparators = [
        StringComparator(
            column="title",
            similarity_function="jaccard",
            preprocess=str.lower,
        ),
        StringComparator(
            column="author",
            similarity_function="jaccard",
            preprocess=str.lower,
        ),
        StringComparator(
            column="isbn_clean",
            similarity_function="jaccard",
            preprocess=str.lower,
        ),
    ]
    matcher = RuleBasedMatcher()
    correspondences = matcher.match(
        df_left=concatenated_df,
        df_right=concatenated_df,
        candidates=candidates,
        comparators=comparators,
        weights=[0.5, 0.3, 0.2],
        threshold=0.7,
    )

    # Perform data fusion
    strategy = DataFusionStrategy("book_fusion_strategy")
    strategy.add_attribute_fuser("title", longest_string)
    strategy.add_attribute_fuser("author", longest_string)
    strategy.add_attribute_fuser("rating", prefer_higher_trust, trust_key="trust_score")
    strategy.add_attribute_fuser(
        "numratings", prefer_higher_trust, trust_key="trust_score"
    )
    strategy.add_attribute_fuser(
        "publisher", prefer_higher_trust, trust_key="trust_score"
    )
    strategy.add_attribute_fuser(
        "publishyear", prefer_higher_trust, trust_key="trust_score"
    )
    strategy.add_attribute_fuser("isbn_clean", longest_string)
    engine = DataFusionEngine(strategy, debug=True)
    fused_df = engine.run(
        datasets=normalized_datasets,
        correspondences=correspondences,
        id_column="id",
        include_singletons=False,
    )

    # Include provenance in the output
    fused_df["provenance"] = fused_df.apply(lambda row: {"source": row["id"]}, axis=1)

    return fused_df


if __name__ == "__main__":
    file_paths = [
        "path/to/amazon.parquet",
        "path/to/goodreads.parquet",
        "path/to/metabooks.parquet",
    ]
    fused_df = main(file_paths)
    fused_df.to_csv("output/fused_books.csv", index=False)
